### ISSUE TITLE
"No results found" when running "index=flurry"

### ISSUE THREAD

**Issue by whizzlearning** [splunk/splunk-app-flurry#2]
As well as the no results found, the 'What to Search' in the Flurry app keeps saying 'Waiting for data...'

First, I double checked the project ID and the password. They both seem to be correct.

Second, I took a look at the jobs and it does seem to run them and complete them against the Flurry interface.

Finally, when I looked into the splunkd.log there are no errors I can find, but I am able to see these messages about Flurry (they are the only ones in the whole log file):

10-22-2013 15:59:34.130 +0800 INFO  HotDBManager - idx=flurry Setting hot mgr params: maxHotSpanSecs=7776000 snapBucketTimespans=false maxHotBuckets=3 maxDataSizeBytes=786432000 quarantinePastSecs=77760000 quarantineFutureSecs=2592000 
10-22-2013 15:59:34.130 +0800 INFO  databasePartitionPolicy - idx=flurry Initialized, params='[...]' isSlave=false needApplyDeleteJournal=false
10-22-2013 15:59:34.130 +0800 INFO  HotDBManager - closing hot mgr for idx=flurry
10-22-2013 15:59:34.130 +0800 INFO  DatabaseDirectoryManager - Writing a bucket manifest in hotWarmPath='/Applications/Splunk/var/lib/splunk/flurry/db'.  Reason='Refreshing manifest.'
10-22-2013 15:59:34.131 +0800 INFO  databasePartitionPolicy - openDatabases complete currentId=0 idx=flurry

Is there anything else I can look at? I am not sure what is going wrong...

Thanks!

**Comment by davidfstr** [comment]
Setup instructions have been modified (actually a long time ago now) to mention the Enable checkbox explicitly. Closing as Fixed.
